list:
    path: /list.php
    defaults:
        _controller: legacy
        _action: indexAction
        _legacy_script: list.php
        
todo:
    path: /todo.php
    defaults:
        _controller: todo
        _action: todoAction
           
