list:
    path: /list.php
    defaults:
        _controller: controller.legacy
        _legacy_script: list.php
        
todo:
    path: /todo.php
    defaults:
        _controller: controller.legacy
        _legacy_script: todo.php
        
test:
    path: /test
    defaults:
        _controller: controller.test
        
