list:
    path: /
    defaults:
        _controller: legacy
        _action: indexAction
        _legacy_script: list.php
        
todo:
    path: /todo/{id}
    defaults:
        _controller: todo
        _action: todoAction
           
